### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by erikbern**

### CODE REVIEW

**Comment by erikbern** [comment]
Sorry didn't mean to push to origin directly – this was a mistake

**Comment by erikbern** [comment]
See https://github.com/erikbern/plaid-python/pull/1

Plaid currently only runs successfully on Python 2.7 unfortunately. I have a separate PR for Python 3 support!

**Comment by erikbern** [comment]
Note that you have to set up Travis and add this repo to make this work!

**Comment by Bpless** [comment]
This is great, we need add a CI to this project!

**Comment by erikbern** [comment]
Great. Btw there's a lot of pep8 violations in the tests so the builds will fail. Should be easy to fix though!

**Pull request merged**
