### PR TITLE
Add support for user data in /item/add_token/create

### PR DESCRIPTION
**Pull request by jwoogerd**
Update the beta `/item/add_token/create` with support for additional user data, which enables more features for returning users.

### CODE REVIEW

**Comment by jwoogerd** [comment]
cc @otherchen, @nathankot

**Comment by jwoogerd** [comment]
@otherchen should I merge this into `plaid:nk-item-add-token-endpoint` or wait until that lands and then rebase onto master?

**Comment by jwoogerd** [comment]
@otherchen Ah sorry, I rebased onto master, which dismissed your approval

**Comment by otherchen** [comment]
@jwoogerd Oops I didn't see these comments until just now 🙈
Rebasing w/ master should be fine :)

**Pull request merged**
