### PR TITLE
Remove type from mfa step methods as it's no longer required

### PR DESCRIPTION
**Pull request by pgorsira**
based on the public documentation here: https://www.plaid.com/docs/#mfa-authentication

### CODE REVIEW

**Comment by ctrembl** [comment]
Thanks @pgorsira!

`type` is only required for MFA step calls when testing with the sandbox credentials, so it may make sense to throw a catch for when 'plaid_test' and 'plaid_good' are used. Otherwise, sandbox calls won't work! Let me know if you have any questions.

**Comment by pgorsira** [comment]
how legit is storing type vs storing id of the institution in my db to represent a bank connection? right now im storing the id as opposed to type. can i get away with type?

seems less than ideal having to query /institutions to derive type from id to use this. if type is sufficient (not subject to change) ill just switch to that.

**Comment by pgorsira** [comment]
any word on this? should i rework my schema to store 'type' instead of 'institution_id'?

**Comment by ctrembl** [comment]
@pgorsira - Institution `type` will not change for existing institutions so you should be fine to store type instead of `institution_id`. There is no need to query /institutions just to derive the type each time.

**Pull request closed without merging**
