### PR TITLE
add request_id to error response object

### PR DESCRIPTION
**Pull request by taylorharwin**
add request id to error response
is already in success response header

### CODE REVIEW

**Comment by thomasw** [comment]
I was making some unrelated improvements to plaid-python's error handling in https://github.com/plaid/plaid-python/pull/70 and, after noticing this pull, went ahead and incorporated attaching the request-id to the exception over there.

The test suite issue you attempted to fix is also resolved in https://github.com/plaid/plaid-python/pull/68.

This project might be dead though, so we'll see, I guess.

**Comment by taylorharwin** [comment]
Hi Thomas,

Thanks so much for doing this! I'll see what I can do to get these requests prioritized.

**Comment by thomasw** [comment]
@taylorharwin When I left that comment, I meant it as empathetic to a fellow third party contributor, not as something mean/passive aggressive directed towards a maintainer. Sorry. :(

**Comment by michaelckelly** [comment]
@taylorharwin I'm going to go ahead and close this pull request but we can move it to https://github.com/plaid/plaid-python-legacy/

**Pull request closed without merging**
