### PR TITLE
Parse floats as Decimal from JSON replies

### LINKED ISSUE #136: Return `Decimal`s instead of `floats`?
Hi.  I was playing with the SDK and noticed I was getting float values back from the calls. 
This means that if you try to use these numbers you might hit weird floating point math issues.

A quick solution is to add `parse_float=Decimal`  to `json.loads` would that be possible, or at least configurable?

### PR DESCRIPTION
**Pull request by euresti**
I'd be ok with making it configurable but I figure I would start somewhere.

Fixes #136

### CODE REVIEW

**Comment by glyph** [comment]
@pbernasconi Is there anything we could do to get this integrated / released?

**Comment by rjames86** [comment]
Hey @euresti!

What's the use case for wanting to wrap floats in `Decimal`? My concern here is that there could be unexpected behavior when doing things like serializing an API response without using a custom `JSONEncoder`

**Comment by euresti** [comment]
The reason is that `float` is dangerous when doing any kind of math. 
(https://docs.python.org/3/tutorial/floatingpoint.html) And once it's converted to `float` the damage is done, so you really want to do it in the call to `json.loads`

You're correct that you'll need a JSONEncoder to put it back. That's why I asked about how to make it configurable in some way.

**Comment by euresti** [comment]
Hi @rjames86 let me know if there's a way to move this forward.  I definitely picked the easiest way to implement this but it's definitely not configurable.  Let me know.

**Comment by glyph** [comment]
Reviewing this issue today I noticed that the original question was about "wrapping floats" in `Decimal`, which isn't exactly what this is doing: if you just wanted to wrap them up, you could always just walk over the API response and do `Decimal(some_float)` anywhere you found one.  `parse_float` tells the JSON parser to parse the *string* encountered in the JSON body with the `Decimal` object, so as to avoid losing any precision.

Perhaps the simplest demonstration of this distinction:

```
>>> import json
>>> from decimal import Decimal
>>> json.loads('{"number": 0.10000000000000001}')
{'number': 0.1}
>>> json.loads('{"number": 0.10000000000000001}', parse_float=Decimal)
{'number': Decimal('0.10000000000000001')}
```

**Comment by euresti** [comment]
Howdy.  Any response to glyph's or my comments?

**Comment by zahanm** [comment]
+1 It is dangerous to handle monetary amounts in floating point arithmetic.
I would love to use this configuration, if present.

And yes, we're talking about what @glyph is saying - parsing as `Decimal` (not "wrapping").

@rjames86 ?

**Comment by pbernasconi** [comment]
@euresti – please excuse the lack of response here, we've been debating this change internally and haven't made a decision yet on it.

A few comments however:
* While this change is simple, the implications are broad
  * It's a breaking change for anyone using this library – we'd have to do a major version bump and we will likely see issues where developers do not read the changelog and make the appropriate change on their end
  * I don't see a clear way to make this configurable at the moment

@euresti @glyph would you have a proposal for making this more easily configurable? If we can make it a flag on the request / client, I'd definitely be open to incorporate this change based on that value.

**Comment by glyph** [comment]
@pbernasconi  Thanks for the reply!  To quote @euresti's original submission:

> I'd be ok with making it configurable

😄

**Comment by euresti** [comment]
I'll find a way to make it configurable.  :)

Decimal

**Comment by euresti** [comment]
Closing in favor of #183

**Pull request closed without merging**
