### PR TITLE
Added info_get

### PR DESCRIPTION
**Pull request by erikbern**
This was the one missing method I needed – should probably add the other info* methods as well but it should be trivial

### CODE REVIEW

**Comment by michaelckelly** [comment]
Thanks for the contribution @erikbern - mind adding a corresponding test for this as well?

I've opened an issue (https://github.com/plaid/plaid-python/issues/27) to add full /info support.

**Comment by erikbern** [comment]
Added a test

**Comment by erikbern** [comment]
ping!

**Comment by Bpless** [comment]
Hey @erikbern, this looks great.  Merging!

**Comment by michaelckelly** [comment]
Thanks @erikbern!

**Pull request merged**
